<?php

use Drupal\wwm_utility\Plugin\Block\ContentListingPageTitleBlock;

/**
 * Implements hook_preprocess_page_title().
 */
function wwm_utility_preprocess_page_title(&$variables) {
  $title = ContentListingPageTitleBlock::getTitle();
  if (!empty($title)) {
    $variables['title'] = $title;
  }
}

/**
 * Implements hook_theme().
 */
function wwm_utility_theme() {
  return [
    'webform_handler_wwm_utility_fields_not_equal_summary' => [
      'variables' => ['settings' => NULL, 'handler' => []],
    ],
  ];
}
